---
version: '3'
services:
  chuang-freqtrade:
    image: sojourned/chuang-freqtrade:latest
    # image: sojourned/chuang-freqtrade:latest
    # Use plotting image
    # image: sojourned/chuang-freqtrade:latest
    # Build step - only needed when additional dependencies are needed
    # build:
    #   context: .
    #   dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: chuang-freqtrade
    volumes:
      - "./user_data:/chuang-freqtrade/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/stable/rest-api/ documentation
    # before enabling this.
    ports:
      - "0.0.0.0:8080:8080"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /chuang-freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////chuang-freqtrade/user_data/tradesv3.sqlite
      --config /chuang-freqtrade/user_data/config.json
      --strategy DoubleEMACrossoverWithTrend
